---
#this playbook is to install tomcat.
  - name: Download Tomcat
    get_url: url=http://apachemirror.wuchna.com/tomcat/tomcat-9/v9.0.31/bin/apache-tomcat-9.0.31.tar.gz dest=/opt/SP/apps/tomcat.tar.gz mode=0755 

  - name: Extract Tomcat
    command: "tar zxf /opt/SP/apps/tomcat.tar.gz  -C /opt/SP/apps/tomcat --strip-components 1"
   
  - name: Remove ROOT folder initially
    command: rm -rf /opt/SP/apps/tomcat/webapps/ROOT
    
  - name: Copy DevOps Project War Files
    copy: src=../../../petclinic.war dest=/opt/SP/apps/tomcat/webapps/ROOT.war mode=0644
    notify: 
    - Restart Tomcat
